medicospdf/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_script import Manager
from flask_migrate import Migrate, MigrateCommand
from flask_mail import Mail
from flask_share import Share

app = Flask(__name__)
app.config['SECRET_KEY'] = '5791628bb0b13ce0c676dfde280ba245'
app.config['SECURITY_PASSWORD_SALT'] = app.config['SECRET_KEY']
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///site.db'
# app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://pitambar:hello123@localhost/medicospdf'
app.config['SQLALCHEMY_TRACK_NOTIFICATIONS'] = False
db = SQLAlchemy(app)

share = Share(app)

migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)
bcrypt = Bcrypt(app)
login_manager = LoginManager(app)
login_manager.login_view = 'users.login'
login_manager.login_message_category = 'info'
app.config['MAIL_SERVER'] = 'smtp.gmail.com'
app.config['MAIL_PORT'] = 587
app.config['MAIL_USE_TLS'] = True
app.config['MAIL_USERNAME'] = '***********'
app.config['MAIL_PASSWORD'] = '*******'
mail = Mail(app)

from medicospdf.users.routes import users
from medicospdf.slds.routes import slds
from medicospdf.main.routes import main
from medicospdf.errors.handlers import errors

app.register_blueprint(users)
app.register_blueprint(slds)
app.register_blueprint(main)
app.register_blueprint(errors)

with app.app_context():
    if db.engine.url.drivername == 'sqlite':
        migrate.init_app(app, db, render_as_batch=True)
    else:
        migrate.init_app(app, db)

medicospdf/main/routes.py
from flask import render_template, request, Blueprint
from medicospdf.models import Slide, Category
from flask_login import login_user, current_user, logout_user, login_required
from medicospdf.decorators import check_confirmed


main = Blueprint('main', __name__)


@main.route("/", methods = ['GET', 'POST'])
@main.route("/home", methods = ['GET', 'POST'])
@login_required
@check_confirmed
def home():
    cat = Category.query.all()
    page = request.args.get('page', 1, type = int)
    silds = Slide.query.order_by(Slide.date_posted.desc()).paginate(page = page, per_page = 2)
    slides = current_user.followed_posts().paginate(page = page, per_page = 2)
    if request.method == 'POST' and 'tag' in request.form:
        tag = request.form['tag']
        search = '%{}%'.format(tag)
        slides = Slide.query.filter(Slide.title.like(search))
        return render_template('search.html', posts = slides, categories = cat)

    return render_template('home.html', posts=slides, categories = cat, silds = silds)

@main.route('/explore')
@login_required
@check_confirmed
def explore():
    page = request.args.get('page', 1, type = int)
    cats = Category.query.all()
    slides = Slide.query.order_by(Slide.date_posted.desc()).paginate(page = page, per_page = 2)
    return render_template('explore.html', posts = slides, categories = cats)


@main.route("/about")
@login_required
@check_confirmed
def about():
    cat = Category.query.all()
    return render_template('about.html', title='About', categories = cat)

medicospdf/slds/routes.py
from flask import render_template, url_for, flash, redirect, request, jsonify, send_file, send_from_directory, g, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from medicospdf.decorators import check_confirmed
from medicospdf.slds.forms import SlideForm, CommentForm
from medicospdf.models import User, Slide, Comment, Category, followers, Visit
import secrets
import os
from medicospdf import app, db, bcrypt
from PIL import Image
import datetime
from flask_mail import Message
from medicospdf.decorators import check_confirmed


slds = Blueprint('slds', __name__)



def convert_file(file_fn, random_hex):
    file_name = 'http://127.0.0.1:5000/static/slide_files/' + file_fn
    converted_folder = 'medicospdf/static/slide_files'
    output_path = os.path.join(os.getcwd() + '/') + converted_folder + '/' + file_fn
    print(output_path)
    r = os.system('unoconv -f pdf --output='+ output_path + ' ' + file_name)
    if r == 0:
        return random_hex + '.pdf'
    else: 
        msg = 'Document Not Converted'
        return msg

def save_file(form_file):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_file.filename)
    file_fn = random_hex + f_ext
    file_path = os.path.join(app.root_path, 'static/slide_files', file_fn)
    print(file_path)
    form_file.save(file_path)
    file_conv = convert_file(file_fn, random_hex)
    print(file_conv)
    return file_conv, random_hex


@slds.route('/slide/<int:slide_id>', methods= ['GET', 'POST'])
@login_required
@check_confirmed
def slide(slide_id):
    cat = Category.query.all()
    slide = Slide.query.get_or_404(slide_id)
    v = Visit.query.filter_by(id = slide_id).first()
    if not v:
        v = Visit()
        v.count += 1
        db.session.add(v)
    v.count += 1
    db.session.commit()
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(comment = form.comment.data, author = current_user, slide_id = slide.id)
        db.session.add(comment)
        db.session.commit()
        flash('Your comment has been posted.', 'success')
        return redirect(url_for('slds.slide', slide_id = slide.id))
    page = request.args.get('page', 1, type = int)
    comments = Comment.query.filter_by(slide_id = slide.id).paginate(page, per_page = 2)
    return render_template('slide.html', title = slide.title, 
                        slide = slide, comments = comments, 
                        form = form, legend = Slide, categories = cat, visitors = v)


@slds.route('/like', methods = ['GET'])
@login_required
@check_confirmed
def like_action():
    if request.args['action'] == 'like':
        slide = Slide.query.filter_by(id=request.args['slide_id']).first_or_404()
        if current_user.has_liked_slide(slide):
            current_user.unlike_slide(slide)
            db.session.commit()
            like = len(slide.likes)
            return jsonify({'status':'unlike', 'like':like, 'text':'Like'})
        else:
            current_user.like_slide(slide)
            db.session.commit()
            like = len(slide.likes)
            return jsonify({"status": 'liked', 'like':like, 'text':'Liked'})

@slds.route('/slide/new', methods = ['GET', 'POST'])
@login_required
@check_confirmed
def new_slide():
    form = SlideForm()
    cat = Category.query.all()
    if form.validate_on_submit():
        if form.file.data:
            uploaded_file, random_hex = save_file(form.file.data)
            print(uploaded_file)
        if uploaded_file == random_hex + '.pdf':
            slide = Slide(title = form.title.data, 
                category_id = form.category.data, description = form.description.data, 
                file = uploaded_file, author = current_user)
            db.session.add(slide)
            db.session.commit()
            flash('Your Slide has been created!!!', 'success')
            return redirect(url_for('slds.new_slide'))
        else:
            flash('Your Slide is not Created!!!', 'danger')
            return redirect(url_for('slds.new_slide'))
    return render_template('create_slide.html', title = 'Add New Slide', form = form, categories = cat)

@slds.route('/download/<name>')
@login_required
@check_confirmed
def download(name):
    path = 'static/slide_files/' + name
    return send_file(path, as_attachment = True)


@slds.route('/delete/<int:slide_id>', methods = ['GET', 'POST'])
@login_required
def delete_slide(slide_id):
    slide = Slide.query.get_or_404(slide_id)
    if slide.author != current_user: #if the user is trying to delete the post of other user then it will be aborted.s
        abort(403)
    db.session.delete(slide)
    db.session.commit()
    flash('Your slide has been deleted!', 'danger')
    return redirect(url_for('account', user_id = slide.author.id))

@slds.route('/category/<int:cat_id>')
@login_required
@check_confirmed
def category(cat_id):
    page = request.args.get('page', 1, type = int)
    cats = Category.query.all()
    cat = Category.query.filter_by(id = cat_id).first_or_404()
    get_cat_prod = Slide.query.filter_by(category_id = cat.id).paginate(page= page, per_page = 2)
    return render_template('category.html', posts = get_cat_prod, categories = cats, cat = cat)

medicospdf/users/routes.py
from flask import render_template, url_for, flash, redirect, request, jsonify, send_file, send_from_directory, g, Blueprint
from medicospdf import db, bcrypt, mail, app
from medicospdf.users.forms import RegistrationForm, LoginForm, RequestResetForm, ResetPasswordForm, UpdateUserForm
from medicospdf.models import User, Slide, Comment, Category, followers, Visit
from flask_login import login_user, current_user, logout_user, login_required
import secrets
import os
from PIL import Image
import datetime
from flask_mail import Message
from itsdangerous import URLSafeTimedSerializer
from medicospdf.decorators import check_confirmed

users = Blueprint('users', __name__)


def save_picture(form_picture):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename) 
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(app.root_path, 'static/profile_pics', picture_fn)

    output_size = (125, 125)        #resizing the image before uploading to the site
    i = Image.open(form_picture)
    i.thumbnail(output_size)
    i.save(picture_path)

    return picture_fn


def send_reset_email(user):
    token = user.get_reset_token()
    msg = Message('Password Reset Request', sender = 'noreply@demo.com', recipients = [user.email])
    msg.body = f'''To reset your password visit the following link
        {url_for('users.reset_token', token=token, _external = True)}
        If you did not make this request then simply igonre this message and no changes will be made.
        '''
    mail.send(msg)

def send_email(to, subject, template):
    msg = Message(subject, recipients = [to], sender = app.config['MAIL_USERNAME'], html = template)
    mail.send(msg)


def generate_confirmation_token(email):
    serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
    return serializer.dumps(email, salt=app.config['SECURITY_PASSWORD_SALT'])

def confirm_token(token, expiration=3600):
    serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
    try:
        email = serializer.loads(
            token,
            salt=app.config['SECURITY_PASSWORD_SALT'],
            max_age=expiration
        )
    except:
        return False
    return email


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username = form.username.data, email = form.email.data, password = hashed_password)
        db.session.add(user)
        db.session.commit()
        token = generate_confirmation_token(user.email)
        confirm_url = url_for('users.confirm_email', token = token, _external = True)
        html = render_template('activate.html', confirm_url = confirm_url)
        subject = "Please confirm your email."
        send_email(user.email, subject, html)
        login_user(user)
        flash('A confirmation mail has been sent via email', 'success')
        # flash(f'Account created for {form.username.data}!', 'success')
        return redirect(url_for('users.unconfirmed'))
    return render_template('register.html', title='Register', form=form)


@users.route('/confirm/<token>')
@login_required
def confirm_email(token):
    try:
        email = confirm_token(token)
    except:
        flash('The Confirmation line is invalid or has expired', 'danger')
    user = User.query.filter_by(email = email).first_or_404()
    if user.confirmed:
        flash('Account already confirmed. Please Login.', 'success')
    else: 
        user.confirmed = True
        user.confirmed_on = datetime.datetime.now()
        db.session.add(user)
        db.session.commit()
        flash('You have confirmed your account. Thanks!', 'success')
    return redirect(url_for('main.home'))

@users.route('/unconfirmed')
@login_required
def unconfirmed():
    if current_user.confirmed:
        return redirect('home')
    flash('Please confirm your account!', 'warning')
    return render_template('unconfirmed.html')

@users.route('/resend')
@login_required
def resend_confirmation():
    token = generate_confirmation_token(current_user.email)
    confirm_url = url_for('users.confirm_email', token = token, _external = True)
    html = render_template('activate.html', confirm_url=confirm_url)
    subject = 'Please confirm your email.'
    send_email(current_user.email, subject, html)
    flash('A new confirmation email has been sent.', 'success')
    return redirect(url_for('users.unconfirmed'))



@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember = form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check username and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route('/account/<int:user_id>')
@login_required
@check_confirmed
def account(user_id):
    page = request.args.get('page', 1, type = int)
    user = User.query.filter_by(id = user_id).first_or_404()
    get_user_prod = Slide.query.filter_by(user_id = user.id).paginate(page = page, per_page = 2)
    if user is None:
        flash('User %s is not found.', username)
        return redirect(url_for('main.home'))
    return render_template('account.html', user = user, slides = get_user_prod, title = 'Account')


@users.route('/follow/<username>')
@login_required
@check_confirmed
def follow(username):
    user = User.query.filter_by(username = username).first()
    # if user in None:
    #     flash('User %s is not found.', username)
    #     return redirect(url_for('home'))
    if user == current_user:
        flash('Your can\'t follow yourself!')
        return redirect(url_for('users.account', user_id = user.id))
    u = current_user.follow(user)
    # if u is None:
    #     flash('Cannot follow' + username + '.')
    #     return redirect(url_for('account', username = user.username))
    db.session.add(u)
    db.session.commit()
    flash('You are following ' + username + '!', 'success')
    return redirect(url_for('users.account', user_id = user.id))

@users.route('/unfollow/<username>')
@login_required
@check_confirmed
def unfollow(username):
    user = User.query.filter_by(username = username).first()
    u = current_user.unfollow(user)
    if u is None:
        flash('Cannot unfollow ' + username + '.')
        return redirect(url_for('users.account', user_id=user.id))
    db.session.add(u)
    db.session.commit()
    flash('You have stopped following ' + username + '.', 'danger')
    return redirect(url_for('users.account', user_id = user.id))


@users.route('/reset_password', methods = ['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title = 'Reset Request', form = form)

@users.route('/reset_password/<token>', methods = ['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your password has been Updated! You are now able to log in', 'success')
        return redirect(url_for('users.login')) 
    return render_template('reset_token.html', title = 'Reset Password', form = form)


@users.route('/update/<int:user_id>', methods = ['GET', 'POST'])
@login_required
def update_user(user_id):
    form = UpdateUserForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account', user_id = current_user.id))
    elif request.method == 'GET':
        form.username.data = current_user.username
    image_file = url_for('static', filename = 'profile_pics/' + current_user.image_file)
    return render_template('update_account.html', title = 'Update Profile', image_file = image_file, form = form)

medicospdf/templates/account.html
{% extends 'layout.html' %}  
{% block content %}

	<div class="content-section">
	  	<div class="media">
	        <img class="rounded-circle account-img" src="{{ url_for('static', filename = 'profile_pics/' + user.image_file) }}">
	        <div class="media-body">
		        <h2 class="account-heading">{{ user.username }}</h2>
		        <p class="text-secondary">{{ user.email }}</p>
				<p>{{ user.followers.count() }} followers | 
					{% if user == current_user %}
						<a href="{{ url_for('users.update_user', user_id = user.id)}}">Edit your profile</a>
					{% elif not current_user.is_following(user) %}
						<a href="{{ url_for('users.follow', username = user.username) }}">Follow</a>
					{% else %}
						<a href="{{ url_for('users.unfollow', username = user.username) }}">Unfollow</a>
					{% endif %}
				</p>
	        </div>
	  	</div>
	  	<div>
	  	{% if slides.items | count == 0 %}
	  		<h1>No posts</h1>
	  	{% else %}
	  		{% for slide in slides.items %}
				<article class="media content-section">
		          <img class="rounded-circle article-img" src="{{ url_for('static', filename = 'profile_pics/' + slide.author.image_file) }}">
		          <div class="media-body">
		            <div class="article-metadata">
		              <a class="mr-2" href="{{ url_for('users.account', user_id = slide.author.id) }}">{{ slide.author.username }}</a>
		              <small class="text-muted">{{ slide.date_posted.strftime('%Y-%m-%d') }}</small>
		            </div>
		            <h2><a class="article-title" href="{{url_for('slds.slide', slide_id = slide.id)}}">{{ slide.title }}</a></h2>
		            <div class="container">
		              <div class="row">
		                <div class="col">
		                  <iframe name="plugin" src="{{ url_for('static', filename = 'slide_files/'+ slide.file) }}" type="application/pdf" width="250" height="215"></iframe>
		                  <div class="row">
		                    <div class="col">
		                      {% if current_user.has_liked_slide(slide) %}
		                       <a class="unlike btn btn-primary" id="like_{{slide.id}}">Liked</a>
		                      {% else %}
		                        <a class="like btn btn-primary" id="like_{{slide.id}}">Like</a>
		                      {% endif %}
		                      <p id = "likeCount_{{slide.id}}">{{ slide.likes | count }}</p>
		                    </div>
		                    <div class="col">
		                      <a href="{{ url_for('slds.download', name = slide.file) }}">
		                      <i class="fa fa-download"></i></a>
		                    </div>
		                  </div>
		                </div>
		                <div class="col">
		                  <p class="article-content text-justify">{{ slide.description | truncate(300)}}<a href="{{ url_for('slds.slide', slide_id = slide.id) }}">show more</a></p>
		                </div>
		              </div>
		            </div>            
		          </div>
		        </article>
	  		{% endfor %}

		  	{% if slides.has_prev %}
		      <a href="{{ url_for('users.account',user_id = user.id, page=slides.prev_num) }}">&lt;&lt; Newer slides</a>
		    {% else %}
		      Newer slides
		    {% endif %} | 
		    {% if slides.has_next %}
		      <a href="{{ url_for('users.account', user_id = user.id, page=slides.next_num) }}">Older slides &gt;&gt;
		      </a>
		    {% else %}
		      Older slides &gt;&gt;
		    {% endif %}
		{% endif %}

	  	</div>
	</div>
{% endblock %}

medicospdf/templates/activate.html
<p>Welcome! Thanks for signing up. Please follow this link to activate your account:</p>
<p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>
<br>
<p>Cheers!</p>

medicospdf/templates/category.html
{% extends 'layout.html' %}
{% block content %}
  {% if posts.items | count == 0 %}
    <h1>No Slides Related to this category.</h1>
  {% else %}
    {% for slide in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename = 'profile_pics/' + slide.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.account', user_id = slide.author.id) }}">{{ slide.author.username }}</a>
              <small class="text-muted">{{ slide.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{url_for('slds.slide', slide_id = slide.id)}}">{{ slide.title }}</a></h2>
            <div class="container">
              <div class="row">
                <div class="col">
                  <iframe name="plugin" src="{{ url_for('static', filename = 'slide_files/'+ slide.file) }}" type="application/pdf" width="300" height="215"></iframe>
                </div>
                <div class="col">
                  <p class="article-content text-justify">{{ slide.description | truncate(300)}}<a href="{{ url_for('slds.slide', slide_id = slide.id) }}">show more</a></p>
                </div>
              </div>
              {% if current_user.has_liked_slide(slide) %}
                <a href="{{ url_for('slds.like_action', slide_id = slide.id, action = 'unlike') }}"><i class="fa fa-heart"></i></a>
              {% else %}
                <a href="{{ url_for('slds.like_action', slide_id = slide.id, action = 'like') }}"><i class="fa fa-heart-o"></i></a>
              {% endif %}
              <p>{{ slide.likes|count }} likes</p>

            </div>            
          </div>
        </article>
    {% endfor %}

    {% if posts.has_prev %}
      <a href="{{ url_for('slds.category',cat_id = cat.id, page=posts.prev_num) }}">&lt;&lt; Newer posts</a>
    {% else %}
      Newer posts
    {% endif %} | 
    {% if posts.has_next %}
      <a href="{{ url_for('slds.category', cat_id = cat.id, page=posts.next_num) }}">Older posts &gt;&gt;
      </a>
    {% else %}
      Older posts &gt;&gt;
    {% endif %}
  {% endif %}


    {% endblock %}

medicospdf/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
      .fa {
        font-size: 25px;
        cursor: pointer;
        user-select: none;
      }

      .fa:hover {
        color: darkblue;
      }

      .fa-heart-o {
        font-size: 25px;
        color: red;
        cursor: pointer;
      }

      .fa-heart {
        font-size: 25px;
        color: red;
        cursor: pointer;
      }
    </style>


    {% if title %}
        <title>MedicosPdf - {{ title }}</title>
    {% else %}
        <title>MedicosPdf</title>
    {% endif %}

    {{ share.load() }}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">MedicosPdf</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class = 'nav-item nav-link' href="{{ url_for('main.explore') }}">Explore</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
              {% block search %}{% endblock %}
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class = 'nav-item nav-link btn btn-outline-primary' href="{{ url_for('slds.new_slide') }}">Upload</a>
                <a class = 'nav-item nav-link' href="{{ url_for('users.account', user_id = current_user.id) }}">Account</a>
                <a class = 'nav-item nav-link' href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        {% if current_user.is_authenticated %}
          <div class="col-md-4">
            <div class="content-section">
              <h3>Categories</h3>
              <p class='text-muted'>
                <ul class="list-group">
                  {% for cat in categories %}
                    <li class="list-group-item list-group-item-light"><a href="{{ url_for('slds.category', cat_id = cat.id) }}">{{ cat.name }}</a></li>
                  {% endfor %}
                </ul>
              </p>
            </div>
          </div>
        {% endif %}
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="http://code.jquery.com/jquery.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

medicospdf/templates/people.html
{% extends 'layout.html' %}

{% block content %}
	{% for user in users %}
		<article class="media content-section">
			<img class="rounded-circle article-img" src="{{ url_for('static', filename = 'profile_pics/' + user.image_file) }}">
				<div class="media-body">
					<div class="article-metadata">
			  			<a href="{{ url_for('account', user_id = user.id) }}">{{ user.username }}</a>
			  		</div>
			  	</div>
			  	<button class="btn btn-primary">follow</button>
		</article>
	{% endfor %}


{% endblock %}

medicospdf/templates/unconfirmed.html
{% extends 'layout.html' %}
{% block content %}

<h1>Welcome!</h1>
<br>
<p>You have not confirmed your account. Please check your inbox (and your spam folder) - you should have received an email with a confirmation link.</p>
<p>Didn't get the email? <a href="{{ url_for('users.resend_confirmation') }}">Resend</a>.</p>
{% endblock %}